spring:
  application:
    name: orders
  config:
    import: "optional:configserver:http://localhost:8070"
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  cloud:
    stream:
      bindings:
        productUpdate-out-0:
          destination: send-productUpdate
      kafka:
        binder:
          broker:
            - localhost:9092

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka